### ISSUE TITLE
invalid syntax in tap!

### ISSUE THREAD

**Issue by Dmole** [anatasof/homebrew-epsxe#5]
```
imac> brew tap anatasof/homebrew-epsxe --verbose --debug
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
==> Tapping anatasof/epsxe
git clone https://github.com/anatasof/homebrew-epsxe /usr/local/Homebrew/Library/Taps/anatasof/homebrew-epsxe --origin=origin --template=
Cloning into '/usr/local/Homebrew/Library/Taps/anatasof/homebrew-epsxe'...
remote: Enumerating objects: 33, done.
remote: Total 33 (delta 0), reused 0 (delta 0), pack-reused 33
Receiving objects: 100% (33/33), 4.14 KiB | 4.14 MiB/s, done.
Resolving deltas: 100% (5/5), done.
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/anatasof/homebrew-epsxe/epsxe.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/anatasof/homebrew-epsxe/epsxe.rb
epsxe: wrong number of arguments (given 1, expected 0)
Error: Cannot tap anatasof/epsxe: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:312:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by mlaopane** [comment]
Got a related issue when following the README

```sh
 ~ brew tap anatasof/homebrew-epsxe                               
 ~ brew install epsxe                                             
Error: epsxe: wrong number of arguments (given 1, expected 0)
```
